# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 355376888e2691e47203d582ded8954925a397deb910540d338c6879e220dd221d8cfac4486377f8e57903ef4a6f16b1cebee9b6dea97852682b2a6eedd5198d

test:
  secret_key_base: 40b127ab587a9e3e5a521341cc330a46ea2afcf81681dbbe60c8ec406286223157fa1cfed4b7fb97e731caf530f20a4db1e6008f86a3af766b54c21ede4a3615

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
